"""empty message

Revision ID: 727961a96878
Revises: 
Create Date: 2023-06-10 18:14:41.455047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "727961a96878"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tally",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("payer", sa.String(), nullable=True),
        sa.Column("payee", sa.String(), nullable=True),
        sa.Column("amount", sa.Float(), nullable=True),
        sa.Column("bill_id", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tally_id"), "tally", ["id"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("hashed_password", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_table(
        "bills",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("amount", sa.Float(), nullable=True),
        sa.Column("payer", sa.String(), nullable=True),
        sa.Column("owed_by", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("group_id", sa.UUID(), nullable=True),
        sa.Column("owner_email", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["owner_email"],
            ["users.email"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_bills_id"), "bills", ["id"], unique=False)
    op.create_table(
        "groups",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("members", sa.ARRAY(sa.String()), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("owner_email", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["owner_email"],
            ["users.email"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_groups_id"), "groups", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_groups_id"), table_name="groups")
    op.drop_table("groups")
    op.drop_index(op.f("ix_bills_id"), table_name="bills")
    op.drop_table("bills")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_tally_id"), table_name="tally")
    op.drop_table("tally")
    # ### end Alembic commands ###
