"""empty message

Revision ID: 9b07c086c932
Revises: 727961a96878
Create Date: 2023-07-18 16:37:19.504258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9b07c086c932"
down_revision = "727961a96878"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tally", sa.Column("payer", sa.String(), nullable=True))
    op.add_column("tally", sa.Column("payee", sa.String(), nullable=True))
    op.drop_column("tally", "user2")
    op.drop_column("tally", "user1")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tally",
        sa.Column("user1", sa.VARCHAR(), autoincrement=False, nullable=True),  # noqa
    )
    op.add_column(
        "tally",
        sa.Column("user2", sa.VARCHAR(), autoincrement=False, nullable=True),  # noqa
    )
    op.drop_column("tally", "payee")
    op.drop_column("tally", "payer")
    # ### end Alembic commands ###
